version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    container_name: grafana-service
    volumes:
      - './grafana/grafana_data:/var/lib/grafana'
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus-service
    volumes:
      - './prometheus/config.yml:/etc/prometheus/prometheus.yml'
  node_exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    container_name: node-exporter-service
