version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    container_name: grafana-service
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus
    volumes:
      - prometheus/config.yaml:/etc/prometheus/prometheus.yml
